### ISSUE TITLE
SignUp not renderding towards Landing page

### ISSUE THREAD

**Issue by Dani-op** [BIT-Studio-OP/CraftMyPortfolio#28]
SIgnup form has slight issue with it after singing up it leads to an empty page where as signing in is working fine after signing in it leads to landing page  

![chrome_jVbFd7nPuY](https://github.com/BIT-Studio-OP/CraftMyPortfolio/assets/81060521/bb06bf3b-5b8e-4732-b17a-ba9ebb4e5183)

**Comment by Jakeclearwater** [comment]
upon trying to resolve this i cant even sign up due this error 
![image](https://github.com/BIT-Studio-OP/CraftMyPortfolio/assets/83677506/57edbca7-3f33-495d-a586-4f17288d9bc1)

**Comment by Perkitw2** [comment]
![Image](https://github.com/BIT-Studio-OP/CraftMyPortfolio/assets/71678612/2c7f56e1-c3fe-41bf-8c81-764c0a87bad5)

Setting up my own account resulted in me just being taken to the main page with no issues.

**Comment by Jakeclearwater** [comment]
We have resolved this, my error was due to not running the emulator and this was also part of Danis error, the function is pointed to firebase but the emulator is not on the firebase database therefore the function was not being triggered. solution is to change the function or navigate manually when testing
