### ISSUE TITLE
backend functionality of updating dropdowns

### ISSUE THREAD

**Issue by Jakeclearwater** [BIT-Studio-OP/CraftMyPortfolio#30]
write code to update the display based off what is entered in dropdowns/onclick text boxes. this needs to refresh the display and be responsive

**Comment by Dani-op** [comment]
Hi Team,
What I have so far is this I'm using the footer as a simple template to alter and save, but right now it's not storing anywhere—it just turns off editing when you press the save button. Please advise on the best way to preserve this file so that it may be retrieved later and returned to the user upon login. Just to be sure I am not straying outside the boundaries of the issue, does issue `backend functionality of updating dropdowns#30` cover the parameters of storing it somewhere as well, or is issue `backend functionality of updating dropdowns#30` restricted to just editing and saving?
Thanks,

Dani.

![chrome_pPKULRz1MU](https://github.com/BIT-Studio-OP/CraftMyPortfolio/assets/81060521/7ebb2668-9df1-4512-8db9-b233b4e62442)
